In [4]:
fichier=open("Causalite semantique pour corpus de document/Leukemia1.txt","r")
print(fichier.read())
fichier.close()

Treatment-related mortality is common among children with acute lymphoblastic leukemia (ALL) treated in poor-resource settings. We applied a simplified flow-cytometric assay to identify patients with precursor B-cell ALL (B-ALL) at very low risk (VLR) of relapse and treated them with a reduced-intensity treatment plan (RELLA05). VLR criteria include favorable presenting features (age ≥1 and <10 years), white blood cell (WBC) count of <50 × 109/L, lack of extramedullary leukemia, and minimal residual disease (MRD) levels of <0.01% on remission induction day 19. Except for two doses of daunorubicin, treatment for patients with VLR B-ALL consisted of a combination of agents with a relatively low myelotoxicity profile, including corticosteroids, vincristine, L-asparaginase, methotrexate, and 6-mercaptopurine. Cyclophosphamide, systemic cytarabine, and CNS radiotherapy were not used. Of 454 patients with ALL treated at the Instituto de Medicina Integral Fernando Figueira in Recife, B

In [2]:
import nltk
from nltk.tokenize import word_tokenize
text = "God is Great! I won a lottery."
print(word_tokenize(text))


['God', 'is', 'Great', '!', 'I', 'won', 'a', 'lottery', '.']


In [12]:
from nltk.corpus import stopwords
fichier=open("Causalite semantique pour corpus de document/Leukemia2.txt","r")
stop = set(stopwords.words('english'))
stop.update(['.', ',', '"', "'", '?', '!', ':', ';', '(', ')', '[', ']', '{', '}'])
tokens = word_tokenize(fichier.read())
tokens = [w for w in tokens if not w in stop]
print(tokens)
fichier.close()

['Adult', 'T-cell', 'leukemia/lymphoma', 'ATL', 'aggressive', 'T-cell', 'neoplasm', 'poor', 'prognosis', 'develops', 'chronic', 'infection', 'human', 'T-cell', 'leukemia', 'virus', 'type', '1', 'HTLV-1', 'Although', 'AMP-activated', 'protein', 'kinase', 'AMPK', 'critical', 'cellular', 'energy', 'sensor', 'recently', 'become', 'clear', 'AMPK', 'act', 'tumor', 'regulator', 'Here', 'assessed', 'expression', 'AMPK', 'primary', 'ATL', 'cells', 'effects', 'dorsomorphin', 'AMPK', 'inhibitor', 'primary', 'ATL', 'cells', 'HTLV-1-infected', 'T-cell', 'lines', 'AMPK', 'expression', 'acute', 'chronic', 'ATL', 'patients', 'significantly', 'higher', 'asymptomatic', 'HTLV-1', 'carriers', 'healthy', 'donors', 'Dorsomorphin', 'induced', 'apoptosis', 'peripheral', 'blood', 'mononuclear', 'cells', 'ATL', 'patients', 'Dorsomorphin', 'also', 'induced', 'dose-', 'time-dependent', 'apoptosis', 'HTLV-1-infected', 'T-cell', 'lines', 'Dorsomorphin', 'increased', 'production', 'intracellular', 'reactive', 'oxyge

In [15]:
from sklearn.feature_extraction.text import CountVectorizer
corpus = ['This is the first document.','This document is the second document.','And this is the third one.','Is this the first document?']
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(corpus)
print(vectorizer.get_feature_names())
print(X.toarray())

['and', 'document', 'first', 'is', 'one', 'second', 'the', 'third', 'this']
[[0 1 1 1 0 0 1 0 1]
 [0 2 0 1 0 1 1 0 1]
 [1 0 0 1 1 0 1 1 1]
 [0 1 1 1 0 0 1 0 1]]


In [1]:
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.pipeline import Pipeline
import numpy as np
corpus = ['this is the first document',
          'this document is the second document',
          'and this is the third one',
          'is this the first document']
vocabulary = ['this', 'document', 'first', 'is', 'second', 'the',
              'and', 'one']
pipe = Pipeline([('count', CountVectorizer(vocabulary=vocabulary)),
                 ('tfid', TfidfTransformer())]).fit(corpus)
pipe['count'].transform(corpus).toarray()




pipe['tfid'].idf_


#pipe.transform(corpus).shape

array([1.        , 1.22314355, 1.51082562, 1.        , 1.91629073,
       1.        , 1.91629073, 1.91629073])